version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=virtusausappointmentdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - /data/mysql
  demo-app:
    image: appointmentapp
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    ports:
      - 8074:8070
    volumes:
      - /data/compose-app